### ISSUE TITLE
? 는 파일 이름에 포함될 수 없다고 합니다.

### ISSUE THREAD

**Issue by Gwonyeong** [monthly-cs/2022-11#1]
git clone 을 이용해 클론을 받아오려 했는데 
![에러](https://user-images.githubusercontent.com/71562311/198504413-08ef74c0-e0fb-450e-bb71-c53a8fb9d810.PNG)

이런 에러가 발생했습니다. 구글링을 해보니 

파일 이름에는 다음 문자를 사용할 수 없습니다.
\ / : * ? " < > |
출처: https://young-cow.tistory.com/47 [어린소:티스토리]

이런 정보를 얻을 수 있었습니다. 기존 "운영체제란?.md" 파일이 원인으로 파악되어 파일 이름을 변경하기로 했습니다!

**Comment by Gwonyeong** [comment]
삭제 후 정상 구동 확인!

**Comment by unchaptered** [comment]
YAHO!
빠르게 해결이 되어서 너무 다행이네요!

**Comment by sumin-dev** [comment]
신기하네요 좋은 정보 감사합니다!(●'◡'●)
