### ISSUE TITLE
대상 운영체제의 제안

### ISSUE THREAD

**Issue by unchaptered** [monthly-cs/2022-11#2]
저희가 어떤 운영체제를 기준으로 CS 를 진행할지, 이야기를 하지 않은 것 같습니다.

이에 동작 원리에 대해서 디테일한 차이가 발생할 수 있을 것 같은 우려가 있습니다.
따라서 2022년 가장 인기있는 OS 중에서 **하나를 선택** 하는 것이 어떤가 합니다.

1. MS-Windows**
2. Ubuntu , `Linux`
3. Mac OS
4. Fedora , `Linux`
5. Solaris , `Oracle`
6. Free BSD , `Unix`
7. Chrome OS , `Linux`
8. CentOS , `Linux`
9. Debian , `Linux`
10. Deepin , `Linux`

> Reference - [hanghae-cs-study/33.컴퓨터를 작동하게 만드는 운영체제.md](https://github.com/unchaptered/hanghae-cs-study/blob/main/docs/33.%EC%BB%B4%ED%93%A8%ED%84%B0%EB%A5%BC%20%EC%9E%91%EB%8F%99%ED%95%98%EA%B2%8C%20%EB%A7%8C%EB%93%9C%EB%8A%94%20%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C.md)

이 부분에 대해서, 어떻게 생각하시는 지 여쭤보고 싶습니다. 😀

@kwanyung  @codeing999  @sumin-dev

**Comment by codeing999** [comment]
아무리 저희가 운영체제를 깊게 판다하여도 
특정 운영체제의 실제 방식까지 들어가는 것은 불필요하기도하고 무리이기도 할 것 같습니다.
운영체제가 발전하면서 나온 여러가지 기초적인 기법들 위주로 공부하게 되지 않을까 싶어서
운영체제를 선택할 필요까진 없지 않을까 생각합니다.

굳이 정하자면 가장 오래전부터 발전해온 리눅스와 그것을 기반으로 한 유닉스가 적절할 것 같긴 합니다.

**Comment by Gwonyeong** [comment]
재철님과 마찬가지 생각입니다. 
각 운영체제의 간단한 특징 정도면 몰라도 특정 운영체제에 대해 깊게 들어갈 필요성은 없다는 생각입니다! 
운영체제가 어떤 역할을 하고 어떤 종류가 있는지 큰 틀에서만 보아도 좋다는 의견입니다~~

**Comment by unchaptered** [comment]
> @codeing999 
> 굳이 정하자면 가장 오래전부터 발전해온 리눅스와 그것을 기반으로 한 유닉스가 적절할 것 같긴 합니다.

그 깊이의 영역이 조금 두리뭉술한 것 같습니다. Monthly-CS 에서 **깊이 있는 공부**라고 원칙을 잡았고 서로에게 도움이 되기 위해서는 가용한 시간 내에서는 깊게 들어가는 것이 좋지않을까 싶습니다.
물론, 한편으로는 시간이 너무 많이 소요될까 걱정이 되기도 하네요.

어느 정도가 저희에게 무리한 깊이일지 예시를 들어주실 수 있을가요?

**Comment by unchaptered** [comment]
> @kwanyung 
> 운영체제가 어떤 역할을 하고 어떤 종류가 있는지 큰 틀에서만 보아도 좋다는 의견입니다~~

혹시 이 부분은 개론 파트에서에 한정된 이야기일까요?

**Comment by unchaptered** [comment]
설명이 조금 부실하였던 것 같아서 덧붙이자면, **CPU Scheduling** 의 경우 **Windows, Ubuntu, Mac** 이 상당히 다르게 작동하고 있는 것으로 알고 있습니다.

- [UK Essays - Compare cpu scheduling of linux and windows](https://www.ukessays.com/essays/information-systems/compare-cpu-scheduling-of-linux-and-windows.php)

**Comment by codeing999** [comment]
@unchaptered 
예시로 들어주신 자료의 경우는 좋은 공부가 될 것이라 생각합니다.

다만 제가 우려했던 부분은
현재의 실제 운영체제들이 쓰는 기법들이, 
저희가 자료 검색이나 책 등을 통해 공부하였을 때 알게 될 기본적인 기법들에서
훨씬 고도화되고 발전되어서 난해해져 있을 가능성이었습니다.

그렇지 않은 경우라면 좋다고 생각합니다.

**Comment by unchaptered** [comment]
> @codeing999 
> 그렇지 않은 경우라면 좋다고 생각합니다.

아하! @codeing999 님이 말씀해주신 부분이 OS 를 실제로 만드는 단계처럼 **너무 깊은 영역**에 대한 공부를 말씀하신 것이었을까요?

**Comment by codeing999** [comment]
@unchaptered 
좀 더 생각해보니, 
어떠한 파트는 그 파트에서 다루는 개념에 대한 원론적인 접근법과 아이디어만 이해해도 충분한 경우가 있겠지만
파트에 따라서는 개발자로써 
현재 우리가 쓰는 운영체제가 어떻게 동작하는지 더 이해가  필요한 부분도 있을 것 같습니다.

운영체제가 하는 역할 중에서도 
하드웨어쪽에 맞닿아 있는 역할들이 상대적으로 저희에게 덜 중요할 것이고
소프트웨어에 맞닿아 있는 역할들은 저희에게 더 중요할 수 있을 것 같습니다.


만약 운영체제 하나를 정해야 한다면 저는 우분투나 윈도우가 좋을 것 같습니다.

**Comment by unchaptered** [comment]
> @codeing999 
> 만약 운영체제 하나를 정해야 한다면 저는 우분투나 윈도우가 좋을 것 같습니다.

오!!! 훨씬 더 명확한 구분이라서 확 와닿는 것 같네요.
다른 분들은 생각이 어떠실 지 궁금하네요.

@kwanyung @sumin-dev

**Comment by Gwonyeong** [comment]
스케줄링을 예시로 보았을 때 여러가지 스케줄링 방식이 있고 각 운영체제에서 특정한 스케줄링 방식을 사용하는 것으로 이해가 됩니다.
제가 정보처리산업기사 자격증을 공부하던 책이나 구글링을 통해 정보를 찾아봐도 운영체제에 따라 프로세스 처리 방식이 바뀌는 등의 분류는 없는걸로 파악됩니다.

본문에 작성해주신 "디테일한 차이"가 스터디의 방향이나 각자의 생각을 바꿀정도로 큰 부분이 아니라는게 제 생각의 결론입니다. 

당장은 할애할 수 있는 시간이 다들 많지 않은만큼 디테일보다는 큰 부분을 우선 이해하고 빠르게 넘어가는게 어떨까 싶어요. 
하지만 운영체제에 따라 크게 좌지우지될 가능성이 있는 개념이라면 정하는게 좋겠지요!(저는 윈도우 맥 우분투 의견입니당.)

**Comment by sumin-dev** [comment]
운영체제별로 동작원리가 다르다면 시장에서 지배적인 운영체제는 깊게 들어갈 필요가 있는 것 같습니다. 개론적인 부분은 말그대로 개괄적으로 배워도 될 것 같지만 깊이 들어가는 세부 목차 안에서는 윈도우, 맥, 리눅스 정도는 차이가 없는지 유심히 살펴 볼 필요가 있다고 생각합니다! 지금 시간이 들더라도 기반을 다져두면 더 좋을 것 같아요. (✿◠‿◠)
그리고 저희가 세심하게 살펴봤다해도 이해의 부족으로 다 파고들지 못한 것일 수 있으니 할 수 있는 만큼에서는 자세한 공부가 도움이 되지 않을까 싶어요!

**Comment by unchaptered** [comment]
요즘 너무 바빠서, @kwanyung님 말씀도 너무 공감이 됩니다.

전체적으로 의견이 살짝 다르지만, 결국은 개인의 가용시간 이슈인 것 같네요.
가용 시간 범위 내, **해당 파트가 개인 및 팀에 도움이 되는 파트**라면 자율적으로 투자해보는 것은 어떨까요?
<br>

@sumin-dev님 말씀처럼, 시장의 주류라면 투자하는 것도 여러 방향으로 흥미로울 것 같아요.

다만, 취업 전후로 많은 일정을 소화해야 하니, 어쩔 수 없는 상황도 있을 것 같네요.
<br>

그럼에도, **중요한 부분이라는 생각**이 들면 공유해보는 것은 어떨까요?
`**.md`에 링크업을 해두고 다른 분과 **공유 연재**나 **릴레이 연재**같은 느낌으로 준비해서 발표하는 것도 재밌을 것 같아요.

그리고 만약에 깊이가 너무 어려움에도 알아야 하거나 알고 싶다면,
지금처럼 Issue를 이용해서 천천히 이를 짚어나가도 흥미로울 것 같네요.

예를 들면,
@codeing999님이 말씀해주신 것처럼 SW와 관련된 부분이면 조금 더 투자해보고 싶은 마음이 드네요.
<br>

다들,
이러한 방식은 어떻게 생각하시는지 궁금합니다!

**Comment by sumin-dev** [comment]
@unchaptered 좋은 의견인 것 같습니다! 각자가 투자할 수 있는 시간이 다르니 한 가지 룰로 모두에게 적용할 순 없을 것 같아요! 저는 제가 부족한 부분은 시간이 되는 선에서는 계속 파고들고 싶다는 생각이 있어서 공부해서 팀에 공유해드리고 싶어요. 자율적으로 진행하는 것에 찬성입니다
@unchaptered 님의 똑똑한 제안과 @codeing999님, @kwanyung 님의 똑똑한 의견 덕분에 저희 스터디가 더 효과적인 방식으로 발전하는 느낌입니다 굿굿👍
