### ISSUE TITLE
문서 양식 제안

### ISSUE THREAD

**Issue by unchaptered** [monthly-cs/2022-11#3]
**2022년 10월 10월 31일, 월요일**에 @kwanyung 님께서 글타래에 다음과 같이 양식에 대해서 주제를 꺼내주셨습니다.

![image](https://user-images.githubusercontent.com/86306802/199010524-276662fe-b996-4d9e-abe8-1e0779689456.png)

이 부분에 대해서, 두 가지 선택지가 있을 것 같은데 여러 분 생각이 어떨지 궁금합니다.

1. 개인이 생각하는 베스트 폼으로 작업 후 **2022년 11월 5일, 토요일**에 양식 투표 및 재수정
2. **2022년 11월 1일, 2일**에 한번 30분 이하로 모여서 폼을 확정하고 작업
3. 일정기한(미정)까지 본인이 생각하는 가장 좋은 폼을 Dooray에 올려서 투표 진행

추가 공수가 사전에 들어가느냐 사후에 들어가느냐 차이인 것 같네요.

@kwanyung @unchaptered @codeing999 @sumin-dev

**Comment by Gwonyeong** [comment]
세 번째 의견인 제 의견은 

기간을 정해놓고 (ex 11월 1일 자정 전까지) 자신이 생각하는 가장 좋은 폼을 Dooray에 올려 투표를 진행하면 좋을 것 같습니다! 

모여서 회의를 진행하기엔 시간 조율이 필요하고 토요일에 양식을 정하면 자료 작성을 2번 해야 한다는 단점이 있다고 생각해요. 

어디까지나 양식을 정하는 것이니까 각자 **간단하게** 작성해서 채팅 채널에 올리면 어떨까요?

**Comment by unchaptered** [comment]
> 세 번째 의견인 제 의견은 기간을 정해놓고 (ex 11월 1일 자정 전까지) 자신이 생각하는 가장 좋은 폼을 Dooray에 올려 투표를 진행하면 좋을 것 같습니다!
> 어디까지나 양식을 정하는 것이니까 각자 **간단하게** 작성해서 채팅 채널에 올리면 어떨까요?

@kwanyung 세 번쨰 선택지로 포함하여 원문 이슈 수정하겠습니다~~~

**Comment by sumin-dev** [comment]
폼 확정 후 1주차 자료들도 수정해야 한다면 저도 @kwanyung 님 의견처럼 미리 폼 확정 후 진행하는 방식이 더 좋은 것 같습니다!

3안에 한 표✔

**Comment by codeing999** [comment]
저도 3번 괜찮네요. 폼은 어떤 파일로 할지도 포함이려나요? 전 노션이 괜찮을거같은데

**Comment by unchaptered** [comment]
그러면 **내일 13:00전**까지 개인별로 간단한 구성 적어서 이 이슈에 코맨트로 달아주시면 될 것 같아요!
투표는 **내일 13:00이후**에 올라온 것에 한정해서 이모티콘 하나씩 눌러주세요!

@codeing999  @sumin-dev @kwanyung @unchaptered

**Comment by unchaptered** [comment]
> 저도 3번 괜찮네요. 폼은 어떤 파일로 할지도 포함이려나요? 전 노션이 괜찮을거같은데

@codeing999 
저희가 *.md 형식으로 **월간 Repository**에 게재하는 형식이기 때문에 markdown 양식이면 크게 상관 없을 것 같습니다!

**Comment by codeing999** [comment]
아 md파일이었죠. 저 근데 낼 2시까지 과제가 있어서 늦게 해야될 것 같습니다.

**Comment by Gwonyeong** [comment]
https://github.com/unchaptered/hanghae-cs-study/blob/main/docs/14.%ED%94%84%EB%A1%9C%EC%84%B8%EC%84%9C%EB%8A%94%20%EB%AC%B4%EC%A1%B0%EA%B1%B4%20%EB%B9%A0%EB%A5%B8%EA%B2%8C%20%EC%A2%8B%EC%9D%84%EA%B9%8C.md

저는 @unchaptered  님의 항해 cs스터디 양식이 좋습니다. 단순히 개념만 적는게 아닌 다른 사람에게 설명하는 방식으로 작성하는 것,  

너무 딱딱하게 작성하지 않는 것, 대주제와 소주제로 나눠서 작성하는 것 등등..

**Comment by unchaptered** [comment]
@kwanyung
저는 여기에서 번호가 있었으면 좋겠어요.

# 1. 프로세스와 스레드
## 1.1. 프로세스와 스레드 차이
## 1.2. 프로세스란?
### 1.2.1. (예시) Chrom 브라우저와 프로세스
### 1.2.2. 결론

이런식으로, 숫자가 있으면 조금 더 보기 편할 것 같아요.

**Comment by sumin-dev** [comment]
저는 글 시작 전, 미니목차(?)를 넣는 것 너무 좋은 것 같습니다! 한눈에 글 전체가 들어와요🙋‍♀️
위에 @kwanyung 님께서 올려주신 @unchaptered 님의 항해cs 링크에 목차가 아주 좋은 예시네요👍

**Comment by codeing999** [comment]
번호도 붙이고 미니목차도 좋고 다 괜찮네요 저도 좋습니다.

**Comment by unchaptered** [comment]
코맨트 확인이 너무 늦어서 죄송합니다ㅠㅠ
그러면 다들 해당 양식으로 진행하는 것으로 알고 있을게요!
@kwanyung @codeing999 @sumin-dev

**Comment by unchaptered** [comment]
@kwanyung  @sumin-dev @codeing999 

1. 문서 최상단에 작성일자및 작성자를 적어보는 건 어떨까요?
2. 문서 최상단에 쓰이는 목차를 ``` 이 기호로 감싸서 블록 처리하는 것에 대해서 어떻게 생각하시나요?

![image](https://user-images.githubusercontent.com/86306802/199751273-e91b7513-e394-4224-a963-702f34a9dde6.png)

**Comment by Gwonyeong** [comment]
> @kwanyung @sumin-dev @codeing999
> 
> 1. 문서 최상단에 작성일자및 작성자를 적어보는 건 어떨까요?
> 2. 문서 최상단에 쓰이는 목차를 ``` 이 기호로 감싸서 블록 처리하는 것에 대해서 어떻게 생각하시나요?
> 
> ![image](https://user-images.githubusercontent.com/86306802/199751273-e91b7513-e394-4224-a963-702f34a9dde6.png)

좋습니다~~

**Comment by codeing999** [comment]
@unchaptered  둘 다 좋네요
